/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlarmList: typeof import('./src/components/AlarmList.vue')['default']
    Equipment: typeof import('./src/components/Equipment.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCarousel: typeof import('naive-ui')['NCarousel']
    NCarouselItem: typeof import('naive-ui')['NCarouselItem']
    NNumberAnimation: typeof import('naive-ui')['NNumberAnimation']
    NProgress: typeof import('naive-ui')['NProgress']
    Pie3DChart: typeof import('./src/components/Pie3DChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheDashboardTitle: typeof import('./src/components/TheDashboardTitle.vue')['default']
    TheMainBoard: typeof import('./src/components/TheMainBoard.vue')['default']
    TheMainTitle: typeof import('./src/components/TheMainTitle.vue')['default']
    ThePercentageRing: typeof import('./src/components/ThePercentageRing.vue')['default']
    TheSubBoard: typeof import('./src/components/TheSubBoard.vue')['default']
  }
}
