shellEmulator: true

trustPolicy: no-downgrade

packages: []

catalogs:
  build:
    '@iconify-json/carbon': ^1.2.15
    '@vitejs/plugin-vue': ^6.0.3
    conventional-changelog-cli: ^5.0.0
    jsdom: ^27.3.0
    unocss: ^66.5.10
    unplugin: ^2.3.11
    unplugin-auto-import: ^20.3.0
    unplugin-vue-components: ^30.0.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-router: ^0.19.1
    vite: ^7.3.0
  dev:
    '@antfu/eslint-config': ^6.7.3
    '@types/echarts': ^5.0.0
    '@types/lodash': ^4.17.21
    '@types/node': ^25.0.3
    '@types/three': ^0.182.0
    '@unocss/eslint-plugin': ^66.5.10
    '@unocss/preset-wind4': ^66.5.10
    '@vue-macros/volar': ^3.1.1
    '@vue/test-utils': ^2.4.6
    archiver: ^7.0.1
    eslint: ^9.39.2
    eslint-plugin-format: ^1.1.0
    lint-staged: ^16.2.7
    sass: ^1.97.1
    sass-embedded: ^1.97.1
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    typescript: ^5.9.3
    vite-plugin-vue-devtools: ^8.0.5
    vite-plugin-vue-layouts: ^0.11.0
    vitest: ^4.0.16
    vue-tsc: ^3.2.1
  frontend:
    '@tensorflow/tfjs': ^4.22.0
    '@tensorflow/tfjs-backend-cpu': ^4.22.0
    '@tensorflow/tfjs-backend-webgl': ^4.22.0
    '@unhead/vue': ^2.0.19
    '@vueuse/core': ^14.1.0
    echarts: ^6.0.0
    echarts-gl: ^2.0.9
    jszip: ^3.10.1
    lil-gui: 0.21.0
    lodash: ^4.17.21
    naive-ui: ^2.43.2
    nanoid: ^5.1.6
    normalize.css: ^8.0.1
    pinia: ^3.0.4
    three: ^0.182.0
    vue: ^3.5.26
    vue-router: ^4.6.4

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
