shellEmulator: true

trustPolicy: no-downgrade

packages: []

catalogs:
  build:
    '@iconify-json/carbon': ^1.2.18
    '@vitejs/plugin-vue': ^6.0.4
    conventional-changelog-cli: ^5.0.0
    jsdom: ^28.1.0
    unocss: ^66.6.2
    unplugin: ^3.0.0
    unplugin-auto-import: ^21.0.0
    unplugin-vue-components: ^31.0.0
    unplugin-vue-macros: ^2.14.5
    unplugin-vue-router: ^0.19.1
    vite: ^7.3.1
  dev:
    '@antfu/eslint-config': ^7.6.1
    '@types/echarts': ^5.0.0
    '@types/lodash': ^4.17.24
    '@types/node': ^25.3.2
    '@types/three': ^0.183.1
    '@unocss/eslint-plugin': ^66.6.2
    '@unocss/preset-wind4': ^66.6.2
    '@vue-macros/volar': ^3.1.2
    '@vue/test-utils': ^2.4.6
    archiver: ^7.0.1
    eslint: ^10.0.2
    eslint-plugin-format: ^2.0.1
    lint-staged: ^16.2.7
    sass: ^1.97.3
    sass-embedded: ^1.97.3
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    typescript: ^5.9.3
    vite-plugin-vue-devtools: ^8.0.6
    vite-plugin-vue-layouts: ^0.11.0
    vitest: ^4.0.18
    vue-tsc: ^3.2.5
  frontend:
    '@tensorflow/tfjs': ^4.22.0
    '@tensorflow/tfjs-backend-cpu': ^4.22.0
    '@tensorflow/tfjs-backend-webgl': ^4.22.0
    '@unhead/vue': ^2.1.9
    '@vueuse/core': ^14.2.1
    echarts: ^6.0.0
    echarts-gl: ^2.0.9
    jszip: ^3.10.1
    lil-gui: 0.21.0
    lodash: ^4.17.23
    naive-ui: ^2.43.2
    nanoid: ^5.1.6
    normalize.css: ^8.0.1
    pinia: ^3.0.4
    three: ^0.183.1
    vue: ^3.5.29
    vue-router: ^5.0.3

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
