/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/bluetooth-json/': RouteRecordInfo<
      '/bluetooth-json/',
      '/bluetooth-json',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ibeacon-simulator/': RouteRecordInfo<
      '/ibeacon-simulator/',
      '/ibeacon-simulator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ibeacon-simulator/components/BeaconCanvas': RouteRecordInfo<
      '/ibeacon-simulator/components/BeaconCanvas',
      '/ibeacon-simulator/components/BeaconCanvas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ibeacon-simulator/components/ControlPanel': RouteRecordInfo<
      '/ibeacon-simulator/components/ControlPanel',
      '/ibeacon-simulator/components/ControlPanel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ibeacon-simulator/components/FormulaPanel': RouteRecordInfo<
      '/ibeacon-simulator/components/FormulaPanel',
      '/ibeacon-simulator/components/FormulaPanel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ibeacon-simulator/components/InfoPanel': RouteRecordInfo<
      '/ibeacon-simulator/components/InfoPanel',
      '/ibeacon-simulator/components/InfoPanel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ibeacon-simulator/components/MessageAlert': RouteRecordInfo<
      '/ibeacon-simulator/components/MessageAlert',
      '/ibeacon-simulator/components/MessageAlert',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/infusion-monitoring/': RouteRecordInfo<
      '/infusion-monitoring/',
      '/infusion-monitoring',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/positioning-algorithms/': RouteRecordInfo<
      '/positioning-algorithms/',
      '/positioning-algorithms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/positioning-algorithms/components/AlgorithmCanvas': RouteRecordInfo<
      '/positioning-algorithms/components/AlgorithmCanvas',
      '/positioning-algorithms/components/AlgorithmCanvas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/positioning-algorithms/components/AlgorithmPanel': RouteRecordInfo<
      '/positioning-algorithms/components/AlgorithmPanel',
      '/positioning-algorithms/components/AlgorithmPanel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/positioning-algorithms/components/ResultPanel': RouteRecordInfo<
      '/positioning-algorithms/components/ResultPanel',
      '/positioning-algorithms/components/ResultPanel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/positioning-algorithms/components/TestPanel': RouteRecordInfo<
      '/positioning-algorithms/components/TestPanel',
      '/positioning-algorithms/components/TestPanel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/bluetooth-json/index.vue': {
      routes:
        | '/bluetooth-json/'
      views:
        | never
    }
    'src/pages/ibeacon-simulator/index.vue': {
      routes:
        | '/ibeacon-simulator/'
      views:
        | never
    }
    'src/pages/ibeacon-simulator/components/BeaconCanvas.vue': {
      routes:
        | '/ibeacon-simulator/components/BeaconCanvas'
      views:
        | never
    }
    'src/pages/ibeacon-simulator/components/ControlPanel.vue': {
      routes:
        | '/ibeacon-simulator/components/ControlPanel'
      views:
        | never
    }
    'src/pages/ibeacon-simulator/components/FormulaPanel.vue': {
      routes:
        | '/ibeacon-simulator/components/FormulaPanel'
      views:
        | never
    }
    'src/pages/ibeacon-simulator/components/InfoPanel.vue': {
      routes:
        | '/ibeacon-simulator/components/InfoPanel'
      views:
        | never
    }
    'src/pages/ibeacon-simulator/components/MessageAlert.vue': {
      routes:
        | '/ibeacon-simulator/components/MessageAlert'
      views:
        | never
    }
    'src/pages/infusion-monitoring/index.vue': {
      routes:
        | '/infusion-monitoring/'
      views:
        | never
    }
    'src/pages/positioning-algorithms/index.vue': {
      routes:
        | '/positioning-algorithms/'
      views:
        | never
    }
    'src/pages/positioning-algorithms/components/AlgorithmCanvas.vue': {
      routes:
        | '/positioning-algorithms/components/AlgorithmCanvas'
      views:
        | never
    }
    'src/pages/positioning-algorithms/components/AlgorithmPanel.vue': {
      routes:
        | '/positioning-algorithms/components/AlgorithmPanel'
      views:
        | never
    }
    'src/pages/positioning-algorithms/components/ResultPanel.vue': {
      routes:
        | '/positioning-algorithms/components/ResultPanel'
      views:
        | never
    }
    'src/pages/positioning-algorithms/components/TestPanel.vue': {
      routes:
        | '/positioning-algorithms/components/TestPanel'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
