/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/ascii-charts/': RouteRecordInfo<
      '/ascii-charts/',
      '/ascii-charts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ascii-charts/components/ChartControls': RouteRecordInfo<
      '/ascii-charts/components/ChartControls',
      '/ascii-charts/components/ChartControls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ascii-charts/components/ChartDisplay': RouteRecordInfo<
      '/ascii-charts/components/ChartDisplay',
      '/ascii-charts/components/ChartDisplay',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bluetooth-json/': RouteRecordInfo<
      '/bluetooth-json/',
      '/bluetooth-json',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/boids-flocking/': RouteRecordInfo<
      '/boids-flocking/',
      '/boids-flocking',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/compass/': RouteRecordInfo<
      '/compass/',
      '/compass',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/compass/components/CompassDial': RouteRecordInfo<
      '/compass/components/CompassDial',
      '/compass/components/CompassDial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/conway-game/': RouteRecordInfo<
      '/conway-game/',
      '/conway-game',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ibeacon-simulator/': RouteRecordInfo<
      '/ibeacon-simulator/',
      '/ibeacon-simulator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ibeacon-simulator/components/BeaconCanvas': RouteRecordInfo<
      '/ibeacon-simulator/components/BeaconCanvas',
      '/ibeacon-simulator/components/BeaconCanvas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ibeacon-simulator/components/ControlPanel': RouteRecordInfo<
      '/ibeacon-simulator/components/ControlPanel',
      '/ibeacon-simulator/components/ControlPanel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ibeacon-simulator/components/FormulaPanel': RouteRecordInfo<
      '/ibeacon-simulator/components/FormulaPanel',
      '/ibeacon-simulator/components/FormulaPanel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ibeacon-simulator/components/InfoPanel': RouteRecordInfo<
      '/ibeacon-simulator/components/InfoPanel',
      '/ibeacon-simulator/components/InfoPanel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ibeacon-simulator/components/MessageAlert': RouteRecordInfo<
      '/ibeacon-simulator/components/MessageAlert',
      '/ibeacon-simulator/components/MessageAlert',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/infusion-monitoring/': RouteRecordInfo<
      '/infusion-monitoring/',
      '/infusion-monitoring',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mnist-data-preview/': RouteRecordInfo<
      '/mnist-data-preview/',
      '/mnist-data-preview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mnist-recognition/': RouteRecordInfo<
      '/mnist-recognition/',
      '/mnist-recognition',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mnist-recognition/components/DrawingCanvas': RouteRecordInfo<
      '/mnist-recognition/components/DrawingCanvas',
      '/mnist-recognition/components/DrawingCanvas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mnist-recognition/components/ModelControls': RouteRecordInfo<
      '/mnist-recognition/components/ModelControls',
      '/mnist-recognition/components/ModelControls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mnist-recognition/components/ModelManager': RouteRecordInfo<
      '/mnist-recognition/components/ModelManager',
      '/mnist-recognition/components/ModelManager',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mnist-recognition/components/PredictionList': RouteRecordInfo<
      '/mnist-recognition/components/PredictionList',
      '/mnist-recognition/components/PredictionList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mnist-recognition/components/TrainingPanel': RouteRecordInfo<
      '/mnist-recognition/components/TrainingPanel',
      '/mnist-recognition/components/TrainingPanel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/n8n-control/': RouteRecordInfo<
      '/n8n-control/',
      '/n8n-control',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/n8n-control/components/VerificationModal': RouteRecordInfo<
      '/n8n-control/components/VerificationModal',
      '/n8n-control/components/VerificationModal',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/pathfinding/': RouteRecordInfo<
      '/pathfinding/',
      '/pathfinding',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/perlin-noise/': RouteRecordInfo<
      '/perlin-noise/',
      '/perlin-noise',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/perlin-noise/components/TerrainCanvas': RouteRecordInfo<
      '/perlin-noise/components/TerrainCanvas',
      '/perlin-noise/components/TerrainCanvas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posture-recognition/': RouteRecordInfo<
      '/posture-recognition/',
      '/posture-recognition',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posture-recognition/components/ParameterControls': RouteRecordInfo<
      '/posture-recognition/components/ParameterControls',
      '/posture-recognition/components/ParameterControls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sensor-dashboard/': RouteRecordInfo<
      '/sensor-dashboard/',
      '/sensor-dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sensor-dashboard/components/CameraPreview': RouteRecordInfo<
      '/sensor-dashboard/components/CameraPreview',
      '/sensor-dashboard/components/CameraPreview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sensor-dashboard/components/DeviceTypeIndicator': RouteRecordInfo<
      '/sensor-dashboard/components/DeviceTypeIndicator',
      '/sensor-dashboard/components/DeviceTypeIndicator',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sensor-dashboard/components/MiniChart': RouteRecordInfo<
      '/sensor-dashboard/components/MiniChart',
      '/sensor-dashboard/components/MiniChart',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sensor-dashboard/components/PermissionButton': RouteRecordInfo<
      '/sensor-dashboard/components/PermissionButton',
      '/sensor-dashboard/components/PermissionButton',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sensor-dashboard/components/SensorCard': RouteRecordInfo<
      '/sensor-dashboard/components/SensorCard',
      '/sensor-dashboard/components/SensorCard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sensor-dashboard/components/SensorGrid': RouteRecordInfo<
      '/sensor-dashboard/components/SensorGrid',
      '/sensor-dashboard/components/SensorGrid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'src/pages/ascii-charts/index.vue': {
      routes:
        | '/ascii-charts/'
      views:
        | never
    }
    'src/pages/ascii-charts/components/ChartControls.vue': {
      routes:
        | '/ascii-charts/components/ChartControls'
      views:
        | never
    }
    'src/pages/ascii-charts/components/ChartDisplay.vue': {
      routes:
        | '/ascii-charts/components/ChartDisplay'
      views:
        | never
    }
    'src/pages/bluetooth-json/index.vue': {
      routes:
        | '/bluetooth-json/'
      views:
        | never
    }
    'src/pages/boids-flocking/index.vue': {
      routes:
        | '/boids-flocking/'
      views:
        | never
    }
    'src/pages/compass/index.vue': {
      routes:
        | '/compass/'
      views:
        | never
    }
    'src/pages/compass/components/CompassDial.vue': {
      routes:
        | '/compass/components/CompassDial'
      views:
        | never
    }
    'src/pages/conway-game/index.vue': {
      routes:
        | '/conway-game/'
      views:
        | never
    }
    'src/pages/ibeacon-simulator/index.vue': {
      routes:
        | '/ibeacon-simulator/'
      views:
        | never
    }
    'src/pages/ibeacon-simulator/components/BeaconCanvas.vue': {
      routes:
        | '/ibeacon-simulator/components/BeaconCanvas'
      views:
        | never
    }
    'src/pages/ibeacon-simulator/components/ControlPanel.vue': {
      routes:
        | '/ibeacon-simulator/components/ControlPanel'
      views:
        | never
    }
    'src/pages/ibeacon-simulator/components/FormulaPanel.vue': {
      routes:
        | '/ibeacon-simulator/components/FormulaPanel'
      views:
        | never
    }
    'src/pages/ibeacon-simulator/components/InfoPanel.vue': {
      routes:
        | '/ibeacon-simulator/components/InfoPanel'
      views:
        | never
    }
    'src/pages/ibeacon-simulator/components/MessageAlert.vue': {
      routes:
        | '/ibeacon-simulator/components/MessageAlert'
      views:
        | never
    }
    'src/pages/infusion-monitoring/index.vue': {
      routes:
        | '/infusion-monitoring/'
      views:
        | never
    }
    'src/pages/mnist-data-preview/index.vue': {
      routes:
        | '/mnist-data-preview/'
      views:
        | never
    }
    'src/pages/mnist-recognition/index.vue': {
      routes:
        | '/mnist-recognition/'
      views:
        | never
    }
    'src/pages/mnist-recognition/components/DrawingCanvas.vue': {
      routes:
        | '/mnist-recognition/components/DrawingCanvas'
      views:
        | never
    }
    'src/pages/mnist-recognition/components/ModelControls.vue': {
      routes:
        | '/mnist-recognition/components/ModelControls'
      views:
        | never
    }
    'src/pages/mnist-recognition/components/ModelManager.vue': {
      routes:
        | '/mnist-recognition/components/ModelManager'
      views:
        | never
    }
    'src/pages/mnist-recognition/components/PredictionList.vue': {
      routes:
        | '/mnist-recognition/components/PredictionList'
      views:
        | never
    }
    'src/pages/mnist-recognition/components/TrainingPanel.vue': {
      routes:
        | '/mnist-recognition/components/TrainingPanel'
      views:
        | never
    }
    'src/pages/n8n-control/index.vue': {
      routes:
        | '/n8n-control/'
      views:
        | never
    }
    'src/pages/n8n-control/components/VerificationModal.vue': {
      routes:
        | '/n8n-control/components/VerificationModal'
      views:
        | never
    }
    'src/pages/pathfinding/index.vue': {
      routes:
        | '/pathfinding/'
      views:
        | never
    }
    'src/pages/perlin-noise/index.vue': {
      routes:
        | '/perlin-noise/'
      views:
        | never
    }
    'src/pages/perlin-noise/components/TerrainCanvas.vue': {
      routes:
        | '/perlin-noise/components/TerrainCanvas'
      views:
        | never
    }
    'src/pages/posture-recognition/index.vue': {
      routes:
        | '/posture-recognition/'
      views:
        | never
    }
    'src/pages/posture-recognition/components/ParameterControls.vue': {
      routes:
        | '/posture-recognition/components/ParameterControls'
      views:
        | never
    }
    'src/pages/sensor-dashboard/index.vue': {
      routes:
        | '/sensor-dashboard/'
      views:
        | never
    }
    'src/pages/sensor-dashboard/components/CameraPreview.vue': {
      routes:
        | '/sensor-dashboard/components/CameraPreview'
      views:
        | never
    }
    'src/pages/sensor-dashboard/components/DeviceTypeIndicator.vue': {
      routes:
        | '/sensor-dashboard/components/DeviceTypeIndicator'
      views:
        | never
    }
    'src/pages/sensor-dashboard/components/MiniChart.vue': {
      routes:
        | '/sensor-dashboard/components/MiniChart'
      views:
        | never
    }
    'src/pages/sensor-dashboard/components/PermissionButton.vue': {
      routes:
        | '/sensor-dashboard/components/PermissionButton'
      views:
        | never
    }
    'src/pages/sensor-dashboard/components/SensorCard.vue': {
      routes:
        | '/sensor-dashboard/components/SensorCard'
      views:
        | never
    }
    'src/pages/sensor-dashboard/components/SensorGrid.vue': {
      routes:
        | '/sensor-dashboard/components/SensorGrid'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
